/*
 * LiquorLEDCodes.h
 *
 *  Created on: Mar 13, 2017
 *      Author: scottireton
 */

#ifndef LIQUORLEDCODES_H_
#define LIQUORLEDCODES_H_


#define SHELFLED_POWER 0xFFE21D

#define SHELFLED_RED 0xFF22DD
#define SHELFLED_GREEN 0xFF02FD
#define SHELFLED_BLUE 0xFFC23D
#define SHELFLED_ORANGE 0xFFE01F
#define SHELFLED_YELLOW 0xFFA857
#define SHELFLED_CYAN 0xFF906F
#define SHELFLED_PURPLE 0xFF6897
#define SHELFLED_WHITE 0xFFB04F

#define SHELFLED_FLASH 0xFF9867
#define SHELFLED_FADE3 0xFF30CF
#define SHELFLED_FADE7 0xFF7A85
#define SHELFLED_JUMP3 0xFF42BD
#define SHELFLED_JUMP7 0xFF52AD
#define SHELFLED_SLOW 0xFF10EF
#define SHELFLED_QUICK 0xFF5AA5
#define SHELFLED_BRIGHTNESS_UP 0xFF18E7
#define SHELFLED_BRIGHTNESS_DOWN 0xFF4AB5
#define SHELFLED_AUTO 0xFF38C7
#define SHELFLED_PLAY_PAUSE 0xFFA25D



#endif /* LIQUORLEDCODES_H_ */
